### ISSUE TITLE
Need to get the summary page sorted out

### ISSUE THREAD

**Issue by davidmce** [eprintsug/bootstrap#10]

**Comment by davidmce** [comment]
@drtjmb do you think we could just copy over the UEL one and take out some bits? Or would you rather we redid it with more mustache.js?

**Comment by drtjmb** [comment]
I would use the UEL one and take out any UEL-specific bits.


Tim?


________________________________

**Comment by davidmce** [comment]
That sounds good. I'll extract them from data.uel when i get time.

**Comment by davidmce** [comment]
solved by #7501241edbc3a71d06584abf77004e7fcd035915

**Comment by davidmce** [comment]
resolved by 7501241edbc3a71d06584abf77004e7fcd035915
